[build]
  publish = "public"
  functions = "functions"
[functions]
  external_node_modules = ["node-fetch", "crypto"]
  node_bundler = "esbuild"
  [functions.upload-file]
    timeout = 30 # 增加到 30 秒
    memory = 512 # 增加到 512MB
